#:kivy 2.3.1

<TimeLabel@MDLabel>
    markup: True
    size_hint: 1, 1
    color: 1,1,1
    font_style: "Title"
    role: "small"
    text_size: self.size
    halign: "center"
    valign: "center"
<Timebox_main>:
    MDBoxLayout:
        size_hint: 1,1
        MDBoxLayout:
            md_bg_color: 1,0,0,.5
            size_hint: .35,1
            orientation: "vertical"
            MDBoxLayout:
                TimeLabel:
                    size_hint_x: .1
                    bold: True
                    text: "1"
                TimeLabel:
                    text: f"{root.start_hours_day_1sm}:{root.start_minutes_day_1sm} - {root.finish_hours_day_1sm}:{root.finish_minutes_day_1sm}"
            MDBoxLayout:
                TimeLabel:
                    size_hint_x: .1
                    bold: True
                    text: "2"
                TimeLabel:
                    text: f"{root.start_hours_day_2sm}:{root.start_minutes_day_2sm} - {root.finish_hours_day_2sm}:{root.finish_minutes_day_2sm}"
        MDBoxLayout:
            size_hint_x: .15
            TimeLabel:
                id: karta_num
                text: root.num_karta
                role: "large"
        MDBoxLayout:
            md_bg_color: 0,0,1,.5
            size_hint_x: .35
            orientation: "vertical"
            MDBoxLayout:
                TimeLabel:
                    size_hint_x: .1
                    bold: True
                    text: "1"
                TimeLabel:
                    text: f"{root.start_hours_end_1sm}:{root.start_minutes_end_1sm} - {root.finish_hours_end_1sm}:{root.finish_minutes_end_1sm}"
            MDBoxLayout:
                TimeLabel:
                    size_hint_x: .1
                    bold: True
                    text: "2"
                TimeLabel:
                    text: f"{root.start_hours_end_2sm}:{root.start_minutes_end_2sm} - {root.finish_hours_end_2sm}:{root.finish_minutes_end_2sm}"
        MDBoxLayout:
            size_hint_x: .2
            Button:
                text: "Удалить"
                on_release: root.del_choice_karta_func(karta_num.text)
    MDDivider:
        size_hint_x: 1
        theme_divider_color: "Custom"
        color: 1,1,1










