#:kivy 2.3.1

<Modal_page_stat>:
    size_hint: (.9,.5)
    title: "Внимание!"
    halign: "center"
    title_size: sp(30)
    bold:True
    title_align: "center"
    MDBoxLayout:
        md_bg_color: .8,.8,.8
        id: root_stat_box
        orientation: "vertical"
        MDBoxLayout:
            orientation: "vertical"
            size_hint_y: .35
            padding: (0,dp(5),0,0)
            spacing: dp(5)
            MDBoxLayout:
                size_hint_y: .15
                TitleLabel:
                    text: f"За [color=#A52A2A][size=20sp]{root.title}[/size][/color] введено: [size=20sp][color=#2E8B40]{root.quant_day}[/color][/size]   дней "
            MDBoxLayout:
                orientation: "vertical"
                size_hint_y: .4
                MDBoxLayout:
                    size_hint_x: 1
                    TitleLabel:
                        text: f"[size=20sp]За месяц отработано:[/size]"
                MDBoxLayout:
                    TitleLabel:
                        role: "large"
                        text: f"[color=#A52A2A]{root.tot_hours}[/color]  часов"
                    TitleLabel:
                        role: "large"
                        text: f"[color=#A52A2A]{root.tot_min}[/color]  минут"
                MDBoxLayout:
                    MDBoxLayout:
                        size_hint_x: .3
                    MDBoxLayout:
                        size_hint_x: .5
                        Button:
                            on_release: root.full_grid_routs()
                            text: "Подробнее"
                            bold: True
                    MDBoxLayout:
                        size_hint_x: .3

        MDDivider:
            pos_hint: {'center_x': .5, 'center_y': .5}
            size_hint_x: .5
            theme_divider_color: "Custom"
            color: 0,0,0
            halign: "center"
        MDBoxLayout:
            orientation: "vertical"
            size_hint_y: .45
            padding: (dp(5),0,dp(5),0)
            MDBoxLayout:
                TitleLabel:
                    text: f"[size=20sp][color=#00008B]{root.curr_date}[/color][/size]"
            MDBoxLayout:
                TitleLabel:
                    text: f"Введён маршрут :"
            MDBoxLayout:
                TitleLabel:
                    text: f" номер [size=20sp][color=#A52A2A]{root.route}[/color][/size]   карта [size=20sp][color=#A52A2A]{root.karta}[/color][/size]"
            MDBoxLayout:
                TitleLabel:
                    text: "Отработано:"
            MDBoxLayout:
                TitleLabel:
                    text: f"[size=20sp][color=#A52A2A]{root.karta_hours}[/color][/size]   часов   [size=20sp][color=#A52A2A]{root.karta_min}[/color][/size]   минут"
