#:kivy 2.3.1

<ModalViewOneRout>:
    MDBoxLayout:
        size_hint: 1,1
        md_bg_color: "black"
        orientation: "vertical"
        MDBoxLayout:
            size_hint: 1,.07
            MDBoxLayout:
                id: box_day
                size_hint_x: .3
                md_bg_color: 1,0,0,.5
                TitleLabel:
                    text: "Будние"
                    color: "white"
            MDBoxLayout:
                id: box_num_route
                size_hint_x: .2# .35
                md_bg_color: "black"
                TitleLabel:
                    font_style: "Display"
                    role: "small"
                    text: root.num_rout
                    color: "white"
                    valign: "top" # ?????????????????????????????????????????
            MDBoxLayout:
                id: box_week
                size_hint_x: .3
                md_bg_color: "blue"
                TitleLabel:
                    text: "Выходные"
                    color: "white"
            MDBoxLayout:
                id: butt_del_karta
                size_hint_x: .2
                md_bg_color: "green"
                TitleLabel:
                    text: "Удалить\n карту"
                    color: "white"
        MDDivider:
            size_hint_x: 1
            theme_divider_color: "Custom"
            color: 1,1,1
        MDBoxLayout:
            size_hint: 1,.9
            orientation: "vertical"
            Grid_for_One_rout:
                id: main_box_time
                row_force_default: True
                row_default_height: sp(28)
        MDBoxLayout:
            id: boxbox
            size_hint: 1,.07
            DelButton:
                id: delbutton
                bold: True
                text:"Удалить маршрут"