#:kivy 2.3.1
<MyPopup_change_route>:
    size_hint: (.9,.5)
    pos_hint: {"x_center": 1,"y": .5}
    title: "Внимание!"
    halign: "center"
    title_size: sp(20)
    title_align: "center"
    separator_color: "blue"
    MDBoxLayout:
        orientation: "vertical"
        MDBoxLayout:
            orientation: "vertical"
            # old time box
            size_hint_y: .5
            MDBoxLayout:
                size_hint_y: .5
                orientation: "vertical"
                TitleLabel:
                    text: f"Маршрут  [size=20sp][color=#B22222]{root.route_str}[/color][/size]  карта [size=20sp][color=#B22222]{root.karta_str}[/color][/size] существует."
                    halign: "center"
                    color: 1,1,1
            MDBoxLayout:
                size_hint_y: .3
                TitleLabel:
                    text: "Время смены"
                    color: 1,1,0
                TitleLabel:
                    text: "Перерыв"
                    color: 1,1,0
            MDBoxLayout:
                size_hint_y: .2
                MDBoxLayout:
                    TitleLabel:
                        text: root.old_start_work
                        color: 1,1,1
                        role: "small"
                        halign: "right"
                    TitleLabel:
                        size_hint_x: .1
                        text: "-"
                        color: 1,1,1
                        role: "small"
                    TitleLabel:
                        text: root.old_end_work
                        color: 1,1,1
                        role: "small"
                        halign: "left"
                MDBoxLayout:
                    TitleLabel:
                        text: root.old_start_lunch
                        color: 1,1,1
                        role: "small"
                        halign: "right"
                    TitleLabel:
                        size_hint_x: .1
                        text: "-"
                        color: 1,1,1
                    TitleLabel:
                        text: root.old_end_lunch
                        color: 1,1,1
                        role: "small"
                        halign: "left"
        MDBoxLayout:
            size_hint_y: .2
            TitleLabel:
                text: "Хотите заменить на:"
                color: 1,0,0
                role: "large"
        MDBoxLayout:
            size_hint_y: .3
            orientation: "vertical"
            MDBoxLayout:
                size_hint_y: .4
                TitleLabel:
                    text: "Время смены"
                    color: 1,1,0
                TitleLabel:
                    text: "Перерыв"
                    color: 1,1,0
            MDBoxLayout:
                size_hint_y: .4
                MDBoxLayout:
                    TitleLabel:
                        text: root.current_start_work
                        color: 1,1,1
                        role: "small"
                        halign: "right"
                    TitleLabel:
                        size_hint_x: .1
                        text: "-"
                        color: 1,1,1
                        role: "small"
                    TitleLabel:
                        text: root.current_end_work
                        color: 1,1,1
                        role: "small"
                        halign: "left"
                MDBoxLayout:
                    TitleLabel:
                        text: root.current_start_lunch
                        color: 1,1,1
                        role: "small"
                        halign: "right"
                    TitleLabel:
                        size_hint_x: .1
                        text: "-"
                        color: 1,1,1
                    TitleLabel:
                        text: root.current_end_lunch
                        color: 1,1,1
                        role: "small"
                        halign: "left"
        MDBoxLayout:
            orientation: "vertical"
            size_hint_y:.2
            MDBoxLayout:
                size_hint_y: .2
                spacing: dp(10)
                Button_main:
                    on_release: root.answer_ok()
                    Button_text:
                        pos_hint: {"center_x": .5,"center_y": .5}
                        text: "Сохранить"
                Button_main:
                    on_release: root.dismiss()
                    Button_text:
                        pos_hint: {"center_x": .5,"center_y": .5}
                        text: "Отмена"