<Page_setting>
    id: page_sett
    name: "setting_page"
    md_bg_color: app.theme_cls.primaryContainerColor # app.theme_cls.primaryColor # app.theme_cls.primaryContainerColor
    MDBoxLayout:
        Button:
            text: "setting"
            on_release:
                root.manager.transition = SlideTransition()
                root.manager.transition.direction = "down"
                root.manager.current = "main_page"